let series={},archive=[],active='QQQ',mode='relative',range='3';document.querySelectorAll('.grid>.panel').forEach(p=>{p.style.height='540px';p.style.overflow='auto'});
const tickers=t=>[...new Set((t.match(/\$[A-Z]{2,5}\b/g)||[]).map(x=>x.slice(1)))]
const esc=t=>t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
function stance(t){
  const s=t.toLowerCase().replace(/&amp;/g,'&');
  // Explicit trade calls carry more weight than incidental adjectives.
  const bull=[['strong buy',4],['i bought',3],['bought $',3],['buying opportunity',3],['great investment',3],['bullish',3],['very bullish',4],['long-term winner',3],['re-rate',2],['rerate',2],['sold out',2],['capacity sold out',2],['positive outlook',2],['hold anyway',2],['promising',2],['tailwind',2],['upside',1],['opportunity',1]];
  const bear=[['shareholder unfriendly',4],['harder to support',4],['incessant capital raise',4],['capital raises',3],['dilution',3],['dropping $',3],['dislike atm',3],['not too bullish',3],['not bullish',3],['bearish',3],['short thesis',3],['avoid',3],['sell/stop loss',3],['wouldn\'t buy',3],['overvalued',3],['too expensive',3],['weak demand',3],['margin pressure',2],['downside',2],['risk',1],['concern',1]];
  const score=rows=>rows.reduce((n,[p,w])=>n+(s.includes(p)?w:0),0), bs=score(bull), rs=score(bear);
  if(rs>bs)return{label:'看空',cls:'bear',score:-1,summary:'偏谨慎，核心判断强调融资、需求或下行风险'};
  if(bs>rs)return{label:'看多',cls:'bull',score:1,summary:'偏积极，核心判断强调买入、增长或基本面支撑'};
  return{label:'中性',cls:'neutral',score:0,summary:'同时包含机会与风险，或缺少明确方向'}
}
function openDetail(t){const z=stance(t.text);modalTitle.textContent=z.label+' · '+tickers(t.text).join(' / ');modalMeta.textContent=t.createdAtISO.replace('T',' ')+' · '+z.summary;modalText.textContent=t.text;modalLink.href='https://x.com/aleabitoreddit/status/'+t.id;modalBackdrop.classList.add('open')}
function pc(a,b){if(a.length<2)return null;const ma=a.reduce((x,y)=>x+y)/a.length,mb=b.reduce((x,y)=>x+y)/b.length;let n=0,x=0,y=0;for(let i=0;i<a.length;i++){n+=(a[i]-ma)*(b[i]-mb);x+=(a[i]-ma)**2;y+=(b[i]-mb)**2}return x&&y?n/Math.sqrt(x*y):0}
function bt(k){const p=series[k]||[],ds=p.map(x=>x[0]),days={};archive.forEach(t=>{if(!tickers(t.text).includes(k))return;const i=ds.findIndex(d=>d>=t.createdAtISO.slice(0,10));if(i<0||i+21>=p.length)return;const sc=stance(t.text).score;if(!sc)return;days[i]??=[];days[i].push(sc)});const a=[],r1=[],r5=[],r21=[],bu=[],be=[];Object.entries(days).forEach(([q,v])=>{q=+q;const sc=v.reduce((x,y)=>x+y)/v.length,base=p[q][1];a.push(sc);r1.push(p[q+1][1]/base-1);r5.push(p[q+5][1]/base-1);r21.push(p[q+21][1]/base-1);if(sc>0)bu.push(r21.at(-1));if(sc<0)be.push(r21.at(-1))});return{n:a.length,c1:pc(a,r1),c5:pc(a,r5),c21:pc(a,r21),bu,be}}
const pct=x=>x==null?'—':(x>=0?'+':'')+(x*100).toFixed(1)+'%';const r=x=>x==null?'—':x.toFixed(2)
function render(){const full=series[active]||[];if(!full.length){chart.innerHTML='<div style="padding:24px;color:#f2b65d">该标的暂无可用日线行情。</div>';return}const cut=new Date();if(range!=='all')cut.setMonth(cut.getMonth()-Number(range));const from=range==='all'?'0000-00-00':cut.toISOString().slice(0,10),s=full.filter(v=>v[0]>=from),dates=s.map(v=>v[0]),y=mode==='relative'?s.map(v=>+(v[1]/s[0][1]*100).toFixed(2)):s.map(v=>v[1]),related=active==='QQQ'?archive.filter(t=>t.createdAtISO.slice(0,10)>=from):archive.filter(t=>tickers(t.text).includes(active)&&t.createdAtISO.slice(0,10)>=from),marks=related.map(t=>{const p=s.find(v=>v[0]>=t.createdAtISO.slice(0,10));const z=stance(t.text);return{x:t.createdAtISO.slice(0,10),y:p?p[1]:null,z,t}}).filter(v=>v.y),my=mode==='relative'?marks.map(v=>+(v.y/s[0][1]*100).toFixed(2)):marks.map(v=>v.y),line={x:dates,y,type:'scatter',mode:'lines',line:{color:'#64d8cb',width:2.5}},points={x:marks.map(v=>v.x),y:my,type:'scatter',mode:'markers+text',text:marks.map(v=>v.z.label),textposition:'top center',textfont:{size:13,color:'#edf3fa'},marker:{size:14,line:{color:'#0b1018',width:2},color:marks.map(v=>v.z.cls==='bull'?'#64d8cb':v.z.cls==='bear'?'#f1789d':'#f2b65d')},customdata:marks.map((v,i)=>i),hovertemplate:'<b>%{text}</b><br>%{x}<br>点击查看详情<extra></extra>'};Plotly.newPlot('chart',[line,points],{margin:{l:55,r:20,t:35,b:42},paper_bgcolor:'#111a26',plot_bgcolor:'#111a26',font:{color:'#edf3fa'},xaxis:{gridcolor:'#263548',type:'date'},yaxis:{gridcolor:'#263548',title:mode==='relative'?'指数（起点=100）':'价格（USD）'},hovermode:'x unified',showlegend:false});document.getElementById('chart').on('plotly_click',e=>{const q=e.points.find(x=>x.data===points);if(q)openDetail(marks[q.customdata].t)});timeline.innerHTML=related.map(t=>{const z=stance(t.text);return'<div class="event"><span class="date">'+t.createdAtISO.slice(0,10)+'</span><span class="ticker">'+tickers(t.text).join(' ')+'</span> <b class="'+z.cls+'">'+z.label+'</b><div>'+z.summary+'</div><p>'+esc(t.text).slice(0,220)+(t.text.length>220?'…':'')+'</p></div>'}).join('');document.querySelectorAll('.event').forEach((e,i)=>e.onclick=()=>openDetail(related[i]));perf.innerHTML=Object.keys(series).map(k=>{const v=series[k].filter(x=>x[0]>=from),h=archive.filter(t=>tickers(t.text).includes(k)).length,p=v.length?v.at(-1)[1]/v[0][1]-1:0;return'<tr><td><button data-sym="'+k+'" style="background:none;border:0;color:#edf3fa;cursor:pointer"><b>'+k+'</b></button></td><td>'+h+'</td><td class="'+(p>=0?'pos':'neg')+'">'+pct(p)+'</td></tr>'}).join('');document.querySelectorAll('[data-sym]').forEach(b=>{b.classList.toggle('active',b.dataset.sym===active);b.onclick=()=>{active=b.dataset.sym;document.getElementById('tickerInput').value=active;render()}})}
async function init(){try{[series,archive]=await Promise.all([fetch('market-data.json').then(r=>r.json()),fetch('archive.json').then(r=>r.json())]);const options=document.getElementById('tickerOptions');Object.keys(series).sort().forEach(k=>{const o=document.createElement('option');o.value=k;options.appendChild(o)});document.getElementById('tickerInput').addEventListener('change',e=>{const k=e.target.value.toUpperCase();if(series[k]){active=k;e.target.value=k;render()}else{e.target.value=active}});document.getElementById('tickerInput').addEventListener('keydown',e=>{if(e.key==='Enter')e.target.dispatchEvent(new Event('change'))});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('rangeSelect').onchange=e=>{range=e.target.value;render()};render()}catch(e){chart.textContent='数据加载失败，请使用本地 HTTP 服务打开。';console.error(e)}}document.getElementById('closeModal').onclick=()=>modalBackdrop.classList.remove('open');document.getElementById('modalBackdrop').onclick=e=>{if(e.target===modalBackdrop)e.currentTarget.classList.remove('open')};init();
